### ISSUE TITLE
Roles and Abilities

### ISSUE THREAD

**Issue by Bill-Williams** [Bill-Williams/SAC#3]
A Club Admin can administrate one or more clubs.
A Club Admin’s abilities above normal user abilities are:
   Maintain Club information for your club(s).
   Create a tournament from a Schedule.
   Maintain all aspects of a tournament.

A Club User can administrate one or more clubs.
A Club User’s abilities above normal user abilities are:
   Maintain an Existing tournament by adding, modifying and deleting Competitors.
   A Club user cannot create a Tournament from a Schedule.
   A Club user cannot Complete a Tournament.

Do we need another Role to manage Schedules, Classes, Colors or Groups?

**Comment by SqlBeast** [comment]
We already have the Scheduler role that will handle the creation of schedules.  If we feel we need a site admin as well we can add that.  For now the tech admin is the only role with access to modify classes, colors, and groups.

**Comment by Bill-Williams** [comment]
Agreed, I just wanted validation from you.  Do you want me to add the logic for those abilities to the app?

**Comment by Bill-Williams** [comment]
Agreed, I just wanted validation from you.  Do you want me to add the logic for those abilities to the app?

**Comment by SqlBeast** [comment]
We do still need a Club User role security so I'll re open this one and use it for that and track here

**Comment by SqlBeast** [comment]
Club User role is setup, also did a bit of refactoring to the extension method to return IQueryable objects so the UI can filter from DB.
